In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("prices_round_0_day_-1.csv", sep=";")

In [5]:
df[df["product"]=="TOMATOES"].bid_price_1.mean()

np.float64(4971.0801)

In [4]:
df[df["product"]=="EMERALDS"].bid_price_1.mean()

np.float64(9992.1264)

In [5]:
df[df["product"]=="EMERALDS"].bid_price_1.mean()

np.float64(9992.1264)

In [6]:
df[df["product"]=="TOMATOES"].bid_price_1.min()

np.int64(4941)

In [7]:
df[df["product"]=="TOMATOES"].bid_price_1.max()

np.int64(5008)

In [8]:
df[df["product"]=="EMERALDS"].bid_price_1.min()

np.int64(9992)

In [9]:
df[df["product"]=="EMERALDS"].bid_price_1.max()

np.int64(10000)

In [10]:
df2 = pd.read_csv("prices_round_0_day_-2.csv", sep=";")

In [11]:
df2[df2["product"]=="EMERALDS"].bid_price_1.mean()

np.float64(9992.1304)

In [12]:
df2.head(20)

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,-2,0,EMERALDS,9992,11,9990,25,NaN,NaN,10008,11,10010,25,NaN,NaN,10000.0,0.0
1,-2,0,TOMATOES,4993,7,4992,17,NaN,NaN,5007,7,5008,17,NaN,NaN,5000.0,0.0
2,-2,100,TOMATOES,4998,5,4993,7,4992.0,16.0,5007,7,5008,16,NaN,NaN,5002.5,0.0
3,-2,100,EMERALDS,9992,15,9990,20,NaN,NaN,10008,15,10010,20,NaN,NaN,10000.0,0.0
4,-2,200,TOMATOES,4994,6,4993,20,NaN,NaN,5008,6,5009,20,NaN,NaN,5001.0,0.0
5,-2,200,EMERALDS,9992,15,9990,30,NaN,NaN,10008,15,10010,30,NaN,NaN,10000.0,0.0
6,-2,300,EMERALDS,9992,13,9990,26,NaN,NaN,10008,13,10010,26,NaN,NaN,10000.0,0.0
7,-2,300,TOMATOES,4995,5,4993,21,NaN,NaN,5008,5,5009,21,NaN,NaN,5001.5,0.0
8,-2,400,EMERALDS,9992,15,9990,20,NaN,NaN,10008,15,10010,20,NaN,NaN,10000.0,0.0
9,-2,400,TOMATOES,4995,8,4993,20,NaN,NaN,5008,8,5009,20,NaN,NaN,5001.5,0.0
10,-2,500,TOMATOES,4994,6,4993,16,NaN,NaN,5008,6,5009,16,NaN,NaN,5001.0,0.0
11,-2,500,EMERALDS,9992,13,9990,30,NaN,NaN,10008,13,10010,30,NaN,NaN,10000.0,0.0
12,-2,600,TOMATOES,4994,9,4992,16,NaN,NaN,5007,9,5008,16,NaN,NaN,5000.5,0.0
13,-2,600,EMERALDS,9992,12,9990,30,NaN,NaN,10008,12,10010,30,NaN,NaN,10000.0,0.0
14,-2,700,EMERALDS,9992,11,9990,27,NaN,NaN,10000,6,10008,11,10010.0,27.0,9996.0,0.0
15,-2,700,TOMATOES,4993,5,4992,17,NaN,NaN,5007,5,5008,17,NaN,NaN,5000.0,0.0
16,-2,800,EMERALDS,9992,15,9990,21,NaN,NaN,10008,15,10010,21,NaN,NaN,10000.0,0.0
17,-2,800,TOMATOES,4993,6,4992,23,NaN,NaN,5007,6,5008,23,NaN,NaN,5000.0,0.0
18,-2,900,TOMATOES,4994,5,4993,24,NaN,NaN,5008,5,5009,24,NaN,NaN,5001.0,0.0
19,-2,900,EMERALDS,9992,13,9990,30,NaN,NaN,10008,13,10010,30,NaN,NaN,10000.0,0.0

In [13]:
df.query("product=='EMERALDS'").head(20)

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
1,-1,0,EMERALDS,9992,14,9990,29,NaN,NaN,10008,14,10010,29,NaN,NaN,10000.0,0.0
2,-1,100,EMERALDS,9992,11,9990,22,NaN,NaN,10008,11,10010,22,NaN,NaN,10000.0,0.0
4,-1,200,EMERALDS,9992,15,9990,20,NaN,NaN,10008,15,10010,20,NaN,NaN,10000.0,0.0
7,-1,300,EMERALDS,9992,11,9990,29,NaN,NaN,10008,11,10010,29,NaN,NaN,10000.0,0.0
9,-1,400,EMERALDS,9992,12,9990,25,NaN,NaN,10008,12,10010,25,NaN,NaN,10000.0,0.0
10,-1,500,EMERALDS,9992,12,9990,30,NaN,NaN,10008,12,10010,30,NaN,NaN,10000.0,0.0
12,-1,600,EMERALDS,9992,11,9990,25,NaN,NaN,10008,11,10010,25,NaN,NaN,10000.0,0.0
15,-1,700,EMERALDS,9992,12,9990,23,NaN,NaN,10008,12,10010,23,NaN,NaN,10000.0,0.0
17,-1,800,EMERALDS,9992,15,9990,29,NaN,NaN,10008,15,10010,29,NaN,NaN,10000.0,0.0
18,-1,900,EMERALDS,9992,15,9990,22,NaN,NaN,10008,15,10010,22,NaN,NaN,10000.0,0.0
20,-1,1000,EMERALDS,9992,13,9990,26,NaN,NaN,10008,13,10010,26,NaN,NaN,10000.0,0.0
23,-1,1100,EMERALDS,9992,12,9990,24,NaN,NaN,10008,12,10010,24,NaN,NaN,10000.0,0.0
25,-1,1200,EMERALDS,9992,11,9990,21,NaN,NaN,10008,11,10010,21,NaN,NaN,10000.0,0.0
26,-1,1300,EMERALDS,9992,10,9990,30,NaN,NaN,10008,10,10010,30,NaN,NaN,10000.0,0.0
28,-1,1400,EMERALDS,9992,14,9990,25,NaN,NaN,10008,14,10010,25,NaN,NaN,10000.0,0.0
31,-1,1500,EMERALDS,9992,10,9990,27,NaN,NaN,10008,10,10010,27,NaN,NaN,10000.0,0.0
33,-1,1600,EMERALDS,9992,13,9990,29,NaN,NaN,10008,13,10010,29,NaN,NaN,10000.0,0.0
34,-1,1700,EMERALDS,9992,12,9990,20,NaN,NaN,10008,12,10010,20,NaN,NaN,10000.0,0.0
36,-1,1800,EMERALDS,9992,15,9990,22,NaN,NaN,10008,15,10010,22,NaN,NaN,10000.0,0.0
39,-1,1900,EMERALDS,9992,14,9990,28,NaN,NaN,10008,14,10010,28,NaN,NaN,10000.0,0.0

In [14]:
df.query("product=='TOMATOES'").head(20)

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,-1,0,TOMATOES,4999,5,4998,15,NaN,NaN,5013,5,5014,15,NaN,NaN,5006.0,0.0
3,-1,100,TOMATOES,5000,8,4998,21,NaN,NaN,5013,8,5014,21,NaN,NaN,5006.5,0.0
5,-1,200,TOMATOES,5000,10,4999,20,NaN,NaN,5013,10,5015,20,NaN,NaN,5006.5,0.0
6,-1,300,TOMATOES,5000,9,4999,21,NaN,NaN,5014,9,5015,21,NaN,NaN,5007.0,0.0
8,-1,400,TOMATOES,5000,5,4999,20,NaN,NaN,5014,5,5015,20,NaN,NaN,5007.0,0.0
11,-1,500,TOMATOES,5000,6,4999,25,NaN,NaN,5014,6,5015,25,NaN,NaN,5007.0,0.0
13,-1,600,TOMATOES,5005,5,5000,8,4999.0,25.0,5014,8,5015,25,NaN,NaN,5009.5,0.0
14,-1,700,TOMATOES,5000,10,4999,18,NaN,NaN,5014,10,5015,18,NaN,NaN,5007.0,0.0
16,-1,800,TOMATOES,5000,8,4998,15,NaN,NaN,5013,8,5014,15,NaN,NaN,5006.5,0.0
19,-1,900,TOMATOES,5000,6,4998,23,NaN,NaN,5013,6,5015,23,NaN,NaN,5006.5,0.0
21,-1,1000,TOMATOES,5000,7,4999,22,NaN,NaN,5014,7,5015,22,NaN,NaN,5007.0,0.0
22,-1,1100,TOMATOES,5007,8,5000,5,4999.0,17.0,5013,5,5015,17,NaN,NaN,5010.0,0.0
24,-1,1200,TOMATOES,5000,6,4999,16,NaN,NaN,5014,6,5015,16,NaN,NaN,5007.0,0.0
27,-1,1300,TOMATOES,5001,9,5000,25,NaN,NaN,5014,9,5016,25,NaN,NaN,5007.5,0.0
29,-1,1400,TOMATOES,5000,9,4999,19,NaN,NaN,5014,9,5015,19,NaN,NaN,5007.0,0.0
30,-1,1500,TOMATOES,5008,8,5000,7,4999.0,21.0,5014,7,5015,21,NaN,NaN,5011.0,0.0
32,-1,1600,TOMATOES,5001,6,4999,19,NaN,NaN,5014,6,5015,19,NaN,NaN,5007.5,0.0
35,-1,1700,TOMATOES,5000,5,4999,15,NaN,NaN,5014,5,5015,15,NaN,NaN,5007.0,0.0
37,-1,1800,TOMATOES,5000,8,4998,17,NaN,NaN,5013,8,5014,17,NaN,NaN,5006.5,0.0
38,-1,1900,TOMATOES,5000,10,4999,20,NaN,NaN,5013,10,5015,20,NaN,NaN,5006.5,0.0

In [6]:
df.shape

(20000, 17)

In [18]:
bid_spike = df.query("product=='TOMATOES' and bid_price_1-bid_price_2>4")

In [19]:
bid_spike.shape

(363, 17)

In [21]:
ask_spike = df.query("product=='TOMATOES' and ask_price_2-ask_price_1>4")

In [23]:
bid_spike

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
13,-1,600,TOMATOES,5005,5,5000,8,4999.0,25.0,5014,8,5015,25,NaN,NaN,5009.5,0.0
22,-1,1100,TOMATOES,5007,8,5000,5,4999.0,17.0,5013,5,5015,17,NaN,NaN,5010.0,0.0
30,-1,1500,TOMATOES,5008,8,5000,7,4999.0,21.0,5014,7,5015,21,NaN,NaN,5011.0,0.0
114,-1,5700,TOMATOES,5003,8,4995,9,4994.0,18.0,5009,9,5010,18,NaN,NaN,5006.0,0.0
274,-1,13700,TOMATOES,5006,5,4998,6,4997.0,23.0,5012,6,5013,23,NaN,NaN,5009.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19854,-1,992700,TOMATOES,4949,6,4944,10,4942.0,24.0,4957,10,4958,24,NaN,NaN,4953.0,0.0
19856,-1,992800,TOMATOES,4951,10,4944,6,4943.0,15.0,4957,6,4958,15,NaN,NaN,4954.0,0.0
19936,-1,996800,TOMATOES,4950,2,4945,10,4944.0,24.0,4958,10,4960,24,NaN,NaN,4954.0,0.0
19990,-1,999500,TOMATOES,4955,5,4950,10,4948.0,23.0,4963,10,4964,23,NaN,NaN,4959.0,0.0
19993,-1,999600,TOMATOES,4955,5,4949,6,4948.0,18.0,4963,6,4964,18,NaN,NaN,4959.0,0.0

In [26]:
ask_spike

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
86,-1,4300,TOMATOES,4995,6,4994,25,NaN,NaN,5002,6,5008,6,5010.0,25.0,4998.5,0.0
212,-1,10600,TOMATOES,5002,6,5000,25,NaN,NaN,5009,4,5015,6,5016.0,25.0,5005.5,0.0
236,-1,11800,TOMATOES,4999,8,4997,25,NaN,NaN,5006,5,5012,8,5013.0,25.0,5002.5,0.0
278,-1,13900,TOMATOES,4997,9,4996,15,NaN,NaN,5004,6,5011,9,5012.0,15.0,5000.5,0.0
293,-1,14600,TOMATOES,4997,9,4995,22,NaN,NaN,5004,2,5010,9,5011.0,22.0,5000.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19920,-1,996000,TOMATOES,4943,7,4942,17,NaN,NaN,4951,6,4957,7,4958.0,17.0,4947.0,0.0
19925,-1,996200,TOMATOES,4943,9,4942,22,NaN,NaN,4950,3,4956,9,4957.0,22.0,4946.5,0.0
19931,-1,996500,TOMATOES,4943,8,4942,23,NaN,NaN,4951,4,4957,8,4958.0,23.0,4947.0,0.0
19933,-1,996600,TOMATOES,4944,6,4942,17,NaN,NaN,4951,4,4957,6,4958.0,17.0,4947.5,0.0
19941,-1,997000,TOMATOES,4945,7,4944,18,NaN,NaN,4952,6,4959,7,4960.0,18.0,4948.5,0.0